### PR TITLE
Migrated code to Swift 3

### PR DESCRIPTION
**Pull request by fluidsonic**
Because Swift 2 and 3 are incompatible :)

You may have to create another branch for this if you also want to support Swift 2 in parallel.

### CODE REVIEW

**Comment by fluidsonic** [comment]
Hey guys. Any news here? :)

**Comment by fluidsonic** [comment]
@cocuroci any news here?
EBANX has missed Swift 3, 3.1, 3.2 and soon 4…

**Comment by cocuroci** [comment]
@fluidsonic 
Sorry for the delay in answering.This week I'm going to review your PR.

**Comment by cocuroci** [comment]
@fluidsonic new version was released

**Pull request merged**
